name: Build App Bundle and APK

on:
  push:
    branches: [master]

jobs:
  build_android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup Java to compile Android project
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.7.12'

      - name: Create the Keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          echo $KEYSTORE_BASE64 | base64 -d > $RUNNER_TEMP/schedcare_key.jks

      - name: Restore packages
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk --release

      - name: Build Android App Bundle
        run: flutter build appbundle --release

      - name: Sign Android App Bundle
        run: jarsigner -verbose -keystore $RUNNER_TEMP/schedcare_key.jks -storepass ${{ secrets.KEYSTORE_PASSWORD }} -keypass ${{ secrets.KEYSTORE_KEY_PASSWORD }} -sigalg SHA256withRSA -digestalg SHA-256 -signedjar build/app/outputs/bundle/release/app-release-signed.aab build/app/outputs/bundle/release/app-release.aab ${{ secrets.KEYSTORE_ALIAS }}

      - name: Sign Android APK
        run: jarsigner -verbose -keystore $RUNNER_TEMP/schedcare_key.jks -storepass ${{ secrets.KEYSTORE_PASSWORD }} -sigalg SHA256withRSA -digestalg SHA-256 build/app/outputs/flutter-apk/app-release.apk ${{ secrets.KEYSTORE_ALIAS }}

#      - name: Publish Android App Bundle
#        uses: actions/upload-artifact@v1
#        with:
#          name: release-aab-signed
#          path: build/app/outputs/bundle/release/app-release-signed.aab
#
#      - name: Publish Android APK
#        uses: actions/upload-artifact@v1
#        with:
#          name: release-apk-signed
#          path: build/app/outputs/flutter-apk/app-release.apk
